// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_S_YOx7EIpyHI4Hu0QvpBZqc5BH6pGLM',
    appId: '1:209020443047:web:d03643ef1c0302740c3e82',
    messagingSenderId: '209020443047',
    projectId: 'nustea-7aba6',
    authDomain: 'nustea-7aba6.firebaseapp.com',
    storageBucket: 'nustea-7aba6.firebasestorage.app',
    measurementId: 'G-K2T2C6MLPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVYo3_zMM_fMTljDhdoIrVTmnjO1M8oEM',
    appId: '1:209020443047:android:5494e9ff3b60be080c3e82',
    messagingSenderId: '209020443047',
    projectId: 'nustea-7aba6',
    storageBucket: 'nustea-7aba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5gpgZ70RvrHMX5jJZPbszDLZw47nLp78',
    appId: '1:209020443047:ios:9181ca9aad7c21440c3e82',
    messagingSenderId: '209020443047',
    projectId: 'nustea-7aba6',
    storageBucket: 'nustea-7aba6.firebasestorage.app',
    iosBundleId: 'com.example.nustea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5gpgZ70RvrHMX5jJZPbszDLZw47nLp78',
    appId: '1:209020443047:ios:9181ca9aad7c21440c3e82',
    messagingSenderId: '209020443047',
    projectId: 'nustea-7aba6',
    storageBucket: 'nustea-7aba6.firebasestorage.app',
    iosBundleId: 'com.example.nustea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_S_YOx7EIpyHI4Hu0QvpBZqc5BH6pGLM',
    appId: '1:209020443047:web:29503d0ab551f6020c3e82',
    messagingSenderId: '209020443047',
    projectId: 'nustea-7aba6',
    authDomain: 'nustea-7aba6.firebaseapp.com',
    storageBucket: 'nustea-7aba6.firebasestorage.app',
    measurementId: 'G-1JGJ24N55F',
  );
}
